{% set name = "analysisstore" %}
{% set version = "0.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/analysisstore-{{ version }}.tar.gz
  sha256: 03306027e95c3df884f47b87e28065e400ac424044e91ced5ed209c56c057439

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - doct
    - six
    - mongoquery
    - jsonschema
    - pymongo
    - pyyaml
    - requests
    - tornado >=5
    - ujson

test:
  imports:
    - analysisstore
    - analysisstore.client
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NSLS-II/analysisstore.git
  summary: Mongo backed data analysis tracker service
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - JunAishima
    - mrakitin
